name = "LIME_JuML"
uuid = "140e1cc2-1c66-4668-82d2-d564195cb585"
authors = ["Peilin Chen <peilin.chen@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ImageSegmentation = "80713f31-8817-5129-9cf8-209ff8fb23e1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Lasso = "b4fcebef-c861-5a0f-a7e2-ba9dc32b180a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VisionHeatmaps = "27106da1-f8bc-4ca8-8c66-9b8289f1e035"
XAIBase = "9b48221d-a747-4c1b-9860-46a1d8ba24a7"

[compat]
Lasso = "0.7"
XAIBase = "3"
julia = "1.10"
